# Generated by Django 5.1.3 on 2024-12-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
    ]
