# Generated by Django 5.1.3 on 2024-12-05 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('litros_vendidos', models.IntegerField()),
                ('total_venta', models.IntegerField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('credito', 'Credito')], max_length=10)),
                ('fecha_compra', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
