# Generated by Django 5.1.3 on 2024-12-05 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
        ('cupon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupon.cupon')),
            ],
        ),
    ]
