# Generated by Django 5.1.3 on 2024-12-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_usuariocupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocupon',
            name='is_valid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
