# Generated by Django 5.1.3 on 2024-12-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_usuariocupon_is_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cupon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
